### ISSUE TITLE
doensn't work in glide 4.0.0

### ISSUE THREAD

**Issue by SolLim** [nguyenhoanglam/ImagePicker#64]
doensn't work in glide 

java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears ...)

**Comment by searchy2** [comment]
Issue #59 
See my PR #58

**Comment by searchy2** [comment]
This library seems to have been abandoned. I recommend https://github.com/Werb/PickPhotoSample 
which I contribute to instead.

**Comment by gabivitcord** [comment]
Yes. It does not work on Glide 4.0.0. What a pity not to update this library...

**Comment by Rainer-Lang** [comment]
The sample is working.

**Comment by nguyenhoanglam** [comment]
@searchy2 Please update to latest version and close this issue if it's works!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I think this issue could be closed.
